### ISSUE TITLE
CI Pipeline Setup with GitHub Actions

### ISSUE THREAD

**Issue by Aky97567** [Aky97567/task-board#4]
# CI Pipeline Setup with GitHub Actions

### Description
Implement a continuous integration pipeline using GitHub Actions to automate testing, linting, and build processes for the project.

### Acceptance Criteria
- [ ] Set up GitHub Actions workflow for PR checks
- [ ] Implement automated testing
- [ ] Configure linting checks
- [ ] Set up build verification
- [ ] Add code coverage reporting
- [ ] Configure branch protection rules
- [ ] Add CI status badges to README

### Technical Steps
1. Create main workflow file (.github/workflows/main.yml):
```yaml
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint
      run: npm run lint
    
    - name: Type check
      run: npm run type-check
    
    - name: Test
      run: npm run test:ci
    
    - name: Build
      run: npm run build

  coverage:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Generate coverage report
      run: npm run test:coverage
```

2. Add NPM scripts to package.json:
```json
{
  "scripts": {
    "type-check": "tsc --noEmit",
    "test:ci": "vitest run",
    "test:coverage": "vitest run --coverage"
  }
}
```

3. Create PR template (.github/pull_request_template.md):
```markdown
## Description
<!-- Describe your changes here -->

## Type of change
- [ ] Bug fix
- [ ] New feature
- [ ] Breaking change
- [ ] Documentation update

## How Has This Been Tested?
<!-- Describe your testing approach here -->

## Checklist
- [ ] My code follows the project's style guidelines
- [ ] I have performed a self-review of my code
- [ ] I have added tests that prove my fix/feature works
- [ ] I have updated the documentation accordingly
```

### Branch Protection Rules
Configure the following in GitHub repository settings:
- Require status checks to pass before merging
- Require branches to be up to date before merging
- Require linear history
- Do not allow bypassing the above settings

### Learning Resources
- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Branch Protection](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches)
- [Status Badges](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge)

### Definition of Done
- CI pipeline successfully runs on all PRs
- All checks (lint, test, build) are automated
- Branch protection rules are in place
- Status badges are visible in README
- PR template is working
- Team members understand the CI process

### Estimated Effort
Small (4-6 hours)
